"use client";

import { useRef, useState } from "react";
import { Sparkles, Send, Loader2, Database, User, Table2 } from "lucide-react";
import { PageHeader } from "@/components/insight";
import { Card } from "@/components/ui/card";
import { AgentChart, AgentTable, type ChartSpec } from "@/components/ask-chart";

type Msg = {
  role: "user" | "assistant";
  text: string;
  sql?: string | null;
  chart?: ChartSpec | null;
  rows?: Record<string, unknown>[];
};

const SUGGESTIONS = [
  "Recovery rate by collection stage",
  "Total arrears and NPF rate by arrears bucket",
  "Promises-to-pay kept vs made by collector",
  "Written-off vs restructured case counts",
];

export default function AskPage() {
  const [messages, setMessages] = useState<Msg[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const sessionId = useRef<string>(Math.random().toString(36).slice(2));
  const scroller = useRef<HTMLDivElement>(null);

  async function send(q: string) {
    const question = q.trim();
    if (!question || loading) return;
    setInput("");
    setMessages((m) => [...m, { role: "user", text: question }]);
    setLoading(true);
    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: question, session_id: sessionId.current }),
      });
      const data = await res.json();
      setMessages((m) => [...m, res.ok
        ? { role: "assistant", text: data.answer || "(no answer)", sql: data.sql, chart: data.chart, rows: data.rows }
        : { role: "assistant", text: `Sorry — the assistant is unavailable (${data.error ?? res.status}).` }]);
    } catch (e) {
      setMessages((m) => [...m, { role: "assistant", text: `Request failed: ${String(e)}` }]);
    } finally {
      setLoading(false);
      requestAnimationFrame(() => scroller.current?.scrollTo({ top: 1e9, behavior: "smooth" }));
    }
  }

  return (
    <div className="space-y-5">
      <PageHeader title="Ask Collections & Recovery" subtitle="Chat about delinquency, arrears, NPF, collection cases, promises-to-pay and recoveries — answers are generated by an ADK agent that writes read-only BigQuery SQL over the collections marts." />

      <Card className="flex h-[calc(100vh-16rem)] flex-col p-0">
        <div ref={scroller} className="flex-1 space-y-4 overflow-y-auto p-5">
          {messages.length === 0 && (
            <div className="flex h-full flex-col items-center justify-center gap-4 text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary"><Sparkles className="h-6 w-6" /></div>
              <div>
                <p className="text-sm font-medium">Ask about collections &amp; recovery</p>
                <p className="mt-1 text-xs text-muted-foreground">Delinquency · arrears · NPF · promises-to-pay · recoveries — Google ADK + Gemini over BigQuery (read-only)</p>
              </div>
              <div className="flex max-w-xl flex-wrap justify-center gap-2">
                {SUGGESTIONS.map((s) => (
                  <button key={s} onClick={() => send(s)}
                    className="rounded-full border bg-card px-3 py-1.5 text-xs text-muted-foreground transition-colors hover:bg-muted hover:text-foreground">
                    {s}
                  </button>
                ))}
              </div>
            </div>
          )}
          {messages.map((m, i) => {
            const wide = m.role === "assistant" && Boolean(m.chart || m.rows?.length);
            return (
            <div key={i} className={`flex gap-3 ${m.role === "user" ? "justify-end" : ""}`}>
              {m.role === "assistant" && <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><Sparkles className="h-4 w-4" /></div>}
              <div className={`${wide ? "w-full max-w-2xl" : "max-w-[80%]"} rounded-xl px-4 py-2.5 text-sm leading-relaxed ${m.role === "user" ? "bg-primary text-primary-foreground" : "border bg-card"}`}>
                <p className="whitespace-pre-wrap">{m.text}</p>
                {m.chart && m.rows?.length ? <AgentChart spec={m.chart} rows={m.rows} /> : null}
                {m.role === "assistant" && m.rows?.length ? (
                  <details className="mt-2 border-t pt-2 text-xs">
                    <summary className="flex cursor-pointer items-center gap-1.5 text-muted-foreground"><Table2 className="h-3.5 w-3.5" /> Data</summary>
                    <div className="mt-2"><AgentTable rows={m.rows} /></div>
                  </details>
                ) : null}
                {m.sql && (
                  <details className="mt-2 border-t pt-2 text-xs">
                    <summary className="flex cursor-pointer items-center gap-1.5 text-muted-foreground"><Database className="h-3.5 w-3.5" /> SQL</summary>
                    <pre className="mt-2 overflow-x-auto whitespace-pre-wrap rounded-md bg-muted p-2 text-[11px] text-muted-foreground">{m.sql}</pre>
                  </details>
                )}
              </div>
              {m.role === "user" && <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-muted"><User className="h-4 w-4" /></div>}
            </div>
            );
          })}
          {loading && (
            <div className="flex gap-3">
              <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><Sparkles className="h-4 w-4" /></div>
              <div className="flex items-center gap-2 rounded-xl border bg-card px-4 py-2.5 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" /> Querying BigQuery…</div>
            </div>
          )}
        </div>

        <form onSubmit={(e) => { e.preventDefault(); send(input); }} className="flex items-center gap-2 border-t p-3">
          <input
            value={input} onChange={(e) => setInput(e.target.value)} disabled={loading}
            placeholder="Ask about arrears, DPD, collection stages, recoveries…"
            className="flex-1 rounded-lg border bg-card px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring disabled:opacity-60"
          />
          <button type="submit" disabled={loading || !input.trim()}
            className="flex items-center gap-1.5 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-opacity disabled:opacity-50">
            <Send className="h-4 w-4" /> Send
          </button>
        </form>
      </Card>
      <p className="text-xs text-muted-foreground">Read-only · scoped to the collections &amp; recovery marts. Answers are AI-generated — verify before acting.</p>
    </div>
  );
}
